site_name: Introduction to mbed BLE

docs_dir: Docs

pages:
- Introduction to mbed BLE: 'index.md'
- Introduction to BLE:
 - 'Section overview': 'Introduction/Overview.md'
 - 'mbed BLE for begginers': 'Introduction/BeginnersIntro.md'
 - 'mbed BLE for developers': 'Introduction/DevIntro.md'
 - 'The mbed BLE API': 'Introduction/BLE_API.md'
 - 'BLE modes and profiles': 'Introduction/BLEInDepth.md'
 - 'Connection parameters': 'Introduction/ConnectionParameters.md'
 - 'Debugging on mbed BLE': 'Introduction/Debugging.md'
 - 'Rapid prototyping on mbed BLE': 'Introduction/Prototyping.md'
 - 'Limitations': 'Introduction/Limitations.md'
- BLE on mbed OS:
 - 'Section overview': 'mbed_OS/Overview.md'
 - 'Creating mbed OS BLE applications': 'mbed_OS/mbed_OS_BLE_Apps.md'
 - 'Review of mbed OS BLE applications': 'mbed_OS/mbed_OS_examples.md'
- BLE on mbed Classic: 
 - 'Section overview': 'mbed_Classic/Overview.md'
 - 'Event-driven programming': 'mbed_Classic/Events.md'
 - 'Tutorial 1: UriBeacon': 'mbed_Classic/URIBeacon.md'
 - 'Tutorial 2: heart rate monitor': 'mbed_Classic/HeartRate.md'
- Advanced samples and features:
 - 'Section overview': 'Advanced/Overview.md'
 - 'Service templates overview': 'Advanced/CreatingServices.md'
 - 'Creating an input service': 'Advanced/InputButton.md'
 - 'Creating an actuator service': 'Advanced/LEDReadWrite.md'
 - 'Custom GAP advertising packet': 'Advanced/CustomGAP.md'
 - 'Custom GATT service with Evothings': 'Advanced/GATTEvo.md'
 - 'The UriBeacon’s advanced features': 'Advanced/URIBeaconAdv.md'
 - 'High data rate, low latency transfers': 'Advanced/HighData.md'
 - 'Firmware Over the Air': 'Advanced/FOTA.md'
 - 'The Nordic DFU boot loader': 'Advanced/Bootloader.md'
- Additional resources:
 - 'Section overview': 'Additional/Overview.md'
 - 'List of abbreviations': 'Additional/Abbr.md'
 - 'FAQ': 'Additional/BLE_FAQ.md'
 - 'Links':'Additional/Links.md'

extra_css: ['FullCSS.css']
