site_name: Introduction to mbed BLE

docs_dir: Docs

pages:
- ['index.md','Introduction to mbed BLE']
- ['Introduction/Overview.md', 'Just a test', 'Section overview']
- ['Introduction/BeginnersIntro.md', 'Just a test', 'mbed BLE for beginners']
- ['Introduction/DevIntro.md', 'Just a test', 'mbed BLE for developers']
- ['Introduction/BLE_API.md', 'Just a test', 'The mbed BLE API']
- ['Introduction/BLEInDepth.md', 'Just a test', 'BLE modes and profiles']
- ['Introduction/ConnectionParameters.md', 'Just a test', 'Connection parameters']
- ['Introduction/Debugging.md', 'Just a test', 'Debugging on mbed BLE']
- ['Introduction/Prototyping.md', 'Just a test', 'Rapid prototyping on mbed BLE']
- ['Introduction/Limitations.md', 'Just a test', 'Limitations']
- ['mbed_OS/Overview.md', 'Just a test', 'Section overview']
- ['mbed_OS/mbed_OS_BLE_Apps.md', 'Just a test', 'Creating mbed OS BLE applications']
- ['mbed_OS/mbed_OS_examples.md', 'Just a test', 'Review of mbed OS BLE applications']
- ['mbed_Classic/Overview.md', 'Just a test', 'Section overview']
- ['mbed_Classic/Events.md', 'Just a test', 'Event-driven programming']
- ['mbed_Classic/URIBeacon.md', 'BLE on mbed Classic', 'Tutorial 1: UriBeacon']
- ['mbed_Classic/HeartRate.md', 'BLE on mbed Classic', 'Tutorial 2: heart rate monitor']
- ['Advanced/Overview.md', 'Advanced samples and features', 'Section overview']
- ['Advanced/CreatingServices.md', 'Advanced samples and features', 'Service templates overview']
- ['Advanced/InputButton.md', 'Advanced samples and features', 'Creating an input service']
- ['Advanced/LEDReadWrite.md', 'Advanced samples and features', 'Creating an actuator service']
- ['Advanced/CustomGAP.md', 'Advanced samples and features', 'Custom GAP advertising packet']
- ['Advanced/GATTEvo.md', 'Advanced samples and features', 'Custom GATT service with Evothings']
- ['Advanced/URIBeaconAdv.md', 'Advanced samples and features', 'The UriBeacon’s advanced features']
- ['Advanced/HighData.md', 'Advanced samples and features', 'High data rate, low latency transfers']
- ['Advanced/FOTA.md', 'Advanced samples and features', 'Firmware Over the Air']
- ['Advanced/Bootloader.md', 'Advanced samples and features', 'The Nordic DFU boot loader']
- ['Additional/Overview.md','Additional resources', 'Section overview']
- ['Additional/Abbr.md','Additional resources', 'List of abbreviations']
- ['Additional/BLE_FAQ.md','Additional resources', 'FAQ']
- ['Additional/Links.md','Additional resources', 'Links']

extra_css: ['FullCSS.css']
